### PR TITLE
added changes from intel

### PR DESCRIPTION
**Pull request by awasayintel**

### CODE REVIEW

**Comment by awasayintel** [comment]
Thanks again for agreeing to include this in your repo :)

**Review by mejbah — COMMENTED** [review]
Thanks for all the updates!  One quick question: Is seems duplicate files are added in the "autoperf/autoperf/..." directory. Am I missing something?

**Comment by awasayintel** [comment]
Of course, thank you for helping with the merge process. 

You are right, sorry about that. Feel free to delete that folder as you merge. Let me know if you would like me to delete it and then send you another request.

**Comment by mejbah** [comment]
As you are more familiar with the new changes, it would be great if you could fix the issue and send another request. How does that sound?

**Comment by awasayintel** [comment]
Absolutely. I am traveling but will do it by the end of the week latest. Thank you so much again!

**Pull request closed without merging**
